run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofumpt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - iface
    - ineffassign
    - interfacebloat
    - intrange
    - lll
    - maintidx
    - mirror
    - misspell
    - nakedret
    - nilnesserr
    - noctx
    - nolintlint
    - nonamedreturns
    - prealloc
    - reassign
    - recvcheck
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - usetesting
    - whitespace
