name: Check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  check-go-mod:
    name: Check Module Tidiness
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 #v6.5.0
        with:
          go-version: '~1.26.0'
      - run: go mod tidy -diff

  check-test-corpus:
    name: Check Test Corpus
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 #v6.5.0
        with:
          go-version: '~1.26.0'
      - run: sudo apt-get install -qy squashfs-tools-ng
      - run: go run ./test/images/gen_images.go ./test/images
      - run: git diff --exit-code --

  check-release-config:
    name: Check Release Config
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 #v6.5.0
        with:
          go-version: '~1.26.0'
      - uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 #v7.2.2
        with:
          args: check
